#!/bin/bash
# COPY-PASTE THESE COMMANDS EXACTLY
# This is the simplest possible way to run the project

echo "===================================="
echo "TurtleBot3 Nav2 - SIMPLE COMMANDS"
echo "===================================="
echo ""
echo "COPY AND RUN THESE IN 3 SEPARATE TERMINALS:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 1 - GAZEBO SIMULATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "export TURTLEBOT3_MODEL=burger"
echo "source /opt/ros/jazzy/setup.bash"
echo "source /home/shrinath/RIS-TurtleBot3-Autonomous-Navigation/install/setup.bash"
echo "ros2 launch my_simulations maze_world.launch.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 2 - NAV2 NAVIGATION (wait 15 sec):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "export TURTLEBOT3_MODEL=burger"
echo "source /opt/ros/jazzy/setup.bash"
echo "source /home/shrinath/RIS-TurtleBot3-Autonomous-Navigation/install/setup.bash"
echo "ros2 launch my_simulations nav2_maze.launch.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 3 - RVIZ VISUALIZATION (wait 10 sec):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "export TURTLEBOT3_MODEL=burger"
echo "source /opt/ros/jazzy/setup.bash"
echo "source /home/shrinath/RIS-TurtleBot3-Autonomous-Navigation/install/setup.bash"
echo "rviz2 -d /home/shrinath/RIS-TurtleBot3-Autonomous-Navigation/config/nav2_default_view.rviz"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "THEN IN RVIZ:"
echo "  1. Click '2D Pose Estimate' button"
echo "  2. Click on map near center (0,0)"
echo "  3. Wait 5 seconds"
echo "  4. Click 'Nav2 Goal' button"
echo "  5. Click destination on map"
echo "  6. Robot navigates! ✅"
echo ""
echo "===================================="
