amcl:
  ros__parameters:
    min_particles: 300
    max_particles: 2000

global_costmap:
  ros__parameters:
    resolution: 0.05
    inflation_layer:
      inflation_radius: 0.28

local_costmap:
  ros__parameters:
    resolution: 0.05
    inflation_layer:
      inflation_radius: 0.25

controller_server:
  ros__parameters:
    FollowPath:
      max_vel_x: 0.25
      max_vel_theta: 1.5
      acc_lim_x: 0.6
      acc_lim_theta: 2.0
